version: "3.9"

services:
  portainer:
    image: portainer/agent:latest
    container_name: portainer-agent
    volumes:
        - ./config/portainer-agent:/data
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped    
    networks:
      automation:
        ipv4_address: ${DOCKER_PORTAINER_AGENT_IP}

networks:
  automation:
    external: true